# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  build:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  
  test:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run: npm run test

  analyze:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run: npm run audit

workflows: 
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test

    